crypto: Don't rely on OpenSSL 1.1.x symbols
Commit e93433fb21231dba2b989b38e058706c3e46d9e2 backports some code
from FreeRDP 3.0. However, such code relies on a symbol not present
in OpenSSL 1.0.x, effectively bumbing the minimum required version:
```
libfreerdp/crypto/crypto.c:953:18: warning: implicit declaration of function 'X509_get0_pubkey'; did you mean 'X509_get_pubkey'? [-Wimplicit-function-declaration]
```

Drop X509_get0_pubkey() usage in favor of X509_get_pubkey(). Free
the returned public key.