shadow: Fix typo with rdpSettings data type
This commit fixes the following compiler error.

FreeRDP/server/shadow/Win/win_wds.c:767:9: error: unknown type name 'rdpSetting';
did you mean 'rdpSettings'?
  767 |         rdpSetting* settings = subsystem->shw->settings;
      |         ^~~~~~~~~~
      |         rdpSettings

The typo was introduced in ba41d5e532121a698b02b00981771802b4fec310 commit.