winpr/crt: fix compatibility with gcc >= 4.9
gcc 4.9 and higher don't allow function redefinition with different
attributes. In crt the functions __lzcnt16 and __lzcnt are defined and
exported. If the definitions don't match build problems might occur when
using winpr with other programs or libraries that also use __lzcnt16 or
similar.

This commit also removes the special handling of 0 for compatibility
along platforms. This situations need to be handled by the caller.

For reference the following error message is show when building a simple test program that also
includes the original definitions:

In file included from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/immintrin.h:55:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/x86intrin.h:46,
                 from test.c:2:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/lzcntintrin.h:39:1: error: redefinition of ‘__lzcnt16’
 __lzcnt16 (unsigned short __X)
 ^
In file included from test.c:1:0:
/opt/freerdp-nightly/include/winpr/crt.h:110:22: note: previous definition of ‘__lzcnt16’ was here
 static INLINE UINT16 __lzcnt16(UINT16 _val16) {