A couple of win32 fixes. Also remove unused winpr/config.h
_InterlockedCompareExchange64 can be an intrinsic on win32.
Must ifndef it or we'll get the following error:
"error C2169: intrinsic function, cannot be defined"

Fix this link error on win32 (needed VCAPITYPE in definition):
tables.obj : unresolved external symbol _sample_VirtualChannelEntry@4