libfreerdp-core: fixed transport
Commit 1daea0d0dc9eb63b6bb1e525e49de82800d34751 introduced an
error: If transport_read_nonblocking returns 0 we may not return
without checking if the ReceiveBuffer is empty.